### PR TITLE
Always initialize dte. Fixes #7

### LINKED ISSUE #7: Null Reference Exception when navigating to Violation in VS 2015-2017
Occurs when the policy had already been initialized. E.g. Excluding then including the pending changes.

### PR DESCRIPTION
**Pull request by tangelov**

### CODE REVIEW

**Review by LockTar — COMMENTED** [review]
I understand that this check should be deleted but can't line 129 go wrong then? Or is SelectedViolation = Violations[ViolationsListView.SelectedIndices[0]]; always selecting the first line? Is that intended?

**Review by LockTar — DISMISSED** [review]

**Comment by tangelov** [comment]
Hi Ralph,

I am assuming you are talking about the check on line 126. Judging by the code, it is intended that the first selected violation be automatically opened if a user presses Enter. I am actually adding a check to prevent error when nothing is selected.

Best Regards,
Teodor

**Comment by LockTar** [comment]
Ok the comment for me was not totally clear. You want to select the first violation instead of just close the dialog. Makes sense. Thank you for the fix.

**Comment by LockTar** [comment]
Released new version with these fixes. v2.3.2

**Pull request merged**
